import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    rudderanalytics?: any;
  }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // RudderStack will be initialized in client components

  return (
    <html lang="en">
      <body className="bg-off-white min-h-screen">
        <Header />
        {children}
        <Script src="/cdp-tracker.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
